version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - ps: .\Deploy\install-fxmicroframework-43-44.ps1

build:
  project: Emitter.sln

after_test:
  - ps: .\Deploy\pack.ps1  

artifacts:
  - path: '**\*.nupkg'